/**
 * Generated by `supabase gen types typescript` once the schema is migrated.
 * For now, a permissive stub so the supabase clients compile.
 */
export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
