# Drop-in for `btl-cron@sync-challenges.timer`
# Copy to: /etc/systemd/system/btl-cron@sync-challenges.timer.d/override.conf
[Timer]
OnCalendar=
OnCalendar=*-*-* 04:30:00     # Once a day at 04:30 UTC
